Resources:
  WebAppBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: bartender-web-app
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration: 
        ErrorDocument: index.html
        IndexDocument: index.html

  WebAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebAppBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref WebAppBucket, '/*']]

  WebAppCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
        # Managed caching optimized policy 
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          TargetOriginId: WebAppOrigin
          ViewerProtocolPolicy: redirect-to-https
        Enabled: Boolean
        HttpVersion: http2and3
        Origins: 
          - CustomOriginConfig: 
              OriginProtocolPolicy: http-only
            DomainName: !GetAtt WebAppBucket.WebsiteURL
            Id: WebAppOrigin

      