name: deploy web app
# Run these on completion of the test workflow
on:
    workflow_run:
        workflows: [test]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            # checkout the codebase
            - uses: actions/checkout@v3
            # setup the node environment
            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  cache: yarn
            # install dependencies and bootstrap monorepo
            - name: Install Dependencies
              run: yarn
            - name: Build Distribution
              run: yarn workspace @bartender/web build
              env:
                VITE_BUILD_NUMBER: ${{ github.run_id }}
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  role-to-assume: arn:aws:iam::580705461669:role/WebAppDeployment
                  aws-region: us-west-2
            - name: Deploy
              run: yarn workspace @bartender/web deploy
