schema: 'http://localhost:4000/local/graphql'
extensions:
  codegen:
    overwrite: true
    generates:
      src/generated/graphql-types.ts:
        plugins:
          - "typescript"
          - "typescript-resolvers"
