service: bartender
provider:
  name: aws
  region: us-west-2
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
plugins:
  - serverless-esbuild
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-stack-output

functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: src/index.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
  ping:
    handler: src/index.ping
    events:
      - http:
          path: ping
          method: get
          cors: true

resources:
  Resources:
    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: primaryId
            AttributeType: S
          - AttributeName: secondaryId
            AttributeType: S
        KeySchema:
          - AttributeName: primaryId
            KeyType: HASH
          - AttributeName: secondaryId
            KeyType: RANGE
        TableName: Drinks-${self:provider.stage}

custom:
  dynamodb:
    start:
      inMemory: true
      migrate: true
    stages:
      - ${self:provider.stage}
  output:
    file: .stacks/${self:provider.stage}.stack.json
