service: bartender
provider:
  name: aws
  region: us-west-2
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-stack-output

functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: src/index.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
  ping:
    handler: src/index.ping
    events:
      - http:
          path: ping
          method: get
          cors: true

custom:
  output:
    file: .stacks/${self:provider.stage}.stack.json
